RegisterNetEvent('dheist:client:heistphone:sendNotification')
AddEventHandler('dheist:client:heistphone:sendNotification', function(message)
    BeginTextCommandThefeedPost("STRING")
    AddTextComponentSubstringPlayerName(message)
    EndTextCommandThefeedPostMessagetext('CHAR_MP_DETONATEPHONE', 'CHAR_MP_DETONATEPHONE', false, 2, 'Kontakt', 'Możliwy napad na Fleccę!')
    EndTextCommandThefeedPostTicker(false, true)
end)